# Generated by Django 3.0.7 on 2020-06-07 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200607_1231'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('user_panel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
