# Generated by Django 3.0.7 on 2020-06-06 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0001_initial'),
        ('post', '0005_auto_20200606_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='user_panel.Users'),
        ),
    ]
